spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://dpg-d1c5c78dl3ps73fahcj0-a:5432/system_for_organizing_exhibitions
    username: jenya
    password: 3fOdDXJzTEZJsSaMGwGqBsgblO7Bqz3Y
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 95039330021-rgr5c6q9mboob215j5772k7bmlvumo8f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

logging:
  level:
    org.springframework.security: DEBUG

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        max-age: 1800
